FinalExam/config/routes.rb
Rails.application.routes.draw do
  resources :addresses

  resources :employees

end

FinalExam/app/models/address.rb
class Address < ActiveRecord::Base
end

FinalExam/app/models/employee.rb
class Employee < ActiveRecord::Base

  belongs_to :address

  def withholding(salary)
    return salary*0.1
  end
end

FinalExam/app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: [:show, :edit, :update, :destroy]

  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = Address.all
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = Address.new(address_params)

    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: 'Address was successfully created.' }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1
  # PATCH/PUT /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to @address, notice: 'Address was successfully updated.' }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to addresses_url, notice: 'Address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_params
      params.require(:address).permit(:city, :street)
    end
end

FinalExam/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

FinalExam/app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:age, :first_name, :last_name, :salary, :address_id)
    end
end

FinalExam/app/helpers/addresses_helper.rb
module AddressesHelper
end

FinalExam/app/helpers/application_helper.rb
module ApplicationHelper
end

FinalExam/app/helpers/employees_helper.rb
module EmployeesHelper
end

FinalExam/app/views/addresses/_form.html.erb
<%= form_for(@address) do |f| %>
  <% if @address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
      <% @address.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :street %><br>
    <%= f.text_field :street %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

FinalExam/app/views/addresses/edit.html.erb
<h1>Editing address</h1>

<%= render 'form' %>

<%= link_to 'Show', @address %> |
<%= link_to 'Back', addresses_path %>

FinalExam/app/views/addresses/index.html.erb
<h1>Listing addresses</h1>

<table>
  <thead>
    <tr>
      <th>City</th>
      <th>Street</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @addresses.each do |address| %>
      <tr>
        <td><%= address.city %></td>
        <td><%= address.street %></td>
        <td><%= link_to 'Show', address %></td>
        <td><%= link_to 'Edit', edit_address_path(address) %></td>
        <td><%= link_to 'Destroy', address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Address', new_address_path %>

FinalExam/app/views/addresses/new.html.erb
<h1>New address</h1>

<%= render 'form' %>

<%= link_to 'Back', addresses_path %>

FinalExam/app/views/addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>City:</strong>
  <%= @address.city %>
</p>

<p>
  <strong>Street:</strong>
  <%= @address.street %>
</p>

<%= link_to 'Edit', edit_address_path(@address) %> |
<%= link_to 'Back', addresses_path %>

FinalExam/app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :salary %><br>
    <%= f.text_field :salary %>
  </div>
  <div class="field">
    <%= f.label :address_id %><br>
    <%= f.collection_select :address_id, Address.all,:id,:street %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

FinalExam/app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

FinalExam/app/views/employees/index.html.erb
<h1>Listing employees</h1>

<table>
  <thead>
    <tr>
      <th>Age</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Salary</th>
      <th>Address</th>
      <th>Tax Owed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.age %></td>
        <td><%= employee.first_name %></td>
        <td><%= employee.last_name %></td>
        <td><%= number_to_currency(employee.salary )%></td>
        <td><%= employee.address.street %></td>
        <td><%= number_to_currency(employee.withholding(employee.salary)) %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

FinalExam/app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

FinalExam/app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Age:</strong>
  <%= @employee.age %>
</p>

<p>
  <strong>First name:</strong>
  <%= @employee.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @employee.last_name %>
</p>

<p>
  <strong>Salary:</strong>
  <%= number_to_currency(@employee.salary) %>
</p>

<p>
<strong>Tax Owed:</strong>
<%= number_to_currency(@employee.withholding(@employee.salary)) %>
</p>

<p>
  <strong>Address:</strong>
  <%= @employee.address.street %>
  <br/>
  <strong>City:</strong>
  <%= @employee.address.city %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

FinalExam/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FinalExam</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>